version: '3.8'

services:
  # 1. PostgreSQL Veritabanı Servisi
  db:
    image: postgres:14
    container_name: minierp-postgres
    environment:
      POSTGRES_DB: minierp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432" # Dışarıdan DB'ye erişmek istenirse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minierp-network

  # 2. Spring Boot Uygulama Servisi
  app:
    build: .
    container_name: minierp-backend
    depends_on:
      - db # DB kalkmadan App kalkmasın
    environment:
      # application.properties içindeki değişkenleri burada set ediyoruz
      DB_URL: jdbc:postgresql://db:5432/minierp_db
      DB_USERNAME: postgres
      DB_PASSWORD: 1
      JWT_SECRET: BURAYA_DOCKER_ICIN_GIZLI_KEY_YAZABILIRSINIZ_XYZ123
    ports:
      - "8080:8080"
    networks:
      - minierp-network

volumes:
  postgres_data:

networks:
  minierp-network:
    driver: bridge